// <auto-generated />
using System;
using IsCool.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IsCool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IsCool.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chats_user_id");

                    b.ToTable("chats");
                });

            modelBuilder.Entity("IsCool.Models.PromptMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("message");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("WhoSent")
                        .HasColumnType("integer")
                        .HasColumnName("who_sent");

                    b.HasKey("Id")
                        .HasName("pk_prompt_messages");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_prompt_messages_chat_id");

                    b.ToTable("prompt_messages");
                });

            modelBuilder.Entity("IsCool.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("PreferredLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_language");

                    b.Property<string>("StudentOf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_of");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("IsCool.Models.Chat", b =>
                {
                    b.HasOne("IsCool.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chats_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IsCool.Models.PromptMessage", b =>
                {
                    b.HasOne("IsCool.Models.Chat", "Chat")
                        .WithMany("PromptMessage")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prompt_messages_chats_chat_id");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("IsCool.Models.Chat", b =>
                {
                    b.Navigation("PromptMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
